const state={sessionId:null,sending:false,messages:[]};
const stages=['define','plan','gather','verify','synthesize','remember'];
const $=id=>document.getElementById(id);
function addMessage(role,text){const node=document.createElement('div');node.className=`message ${role}`;node.textContent=text;$('messages').appendChild(node);node.scrollIntoView({behavior:'smooth',block:'end'});state.messages.push({role,content:text});return node;}
function setStage(stage){const index=stages.indexOf(stage);document.querySelectorAll('.flow-item[data-stage]').forEach((node,i)=>{node.classList.toggle('active',i===index);node.classList.toggle('complete',i<index);const icon=node.querySelector('i');if(icon)icon.textContent=i<index?'✓':i===index?'●':'○';});}
async function request(path,options={},timeoutMs=65000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(path,{headers:{'Content-Type':'application/json'},signal:controller.signal,...options});let data;try{data=await response.json()}catch(_){throw new Error(`API returned invalid JSON (HTTP ${response.status})`)}if(!response.ok)throw new Error(data.detail||data.error||`HTTP ${response.status}`);return data}catch(error){if(error.name==='AbortError')throw new Error('Research request timed out after 65 seconds');throw error}finally{clearTimeout(timer)}}
function setRunning(value){state.sending=value;const button=$('runButton');button.disabled=value;button.innerHTML=value?'Researching… <span>◌</span>':'Start research <span>→</span>';$('prompt').disabled=value;$('researchState').textContent=value?'RUNNING':'READY'}
async function startResearch(prompt){if(state.sending||!prompt)return;if(!state.sessionId)state.sessionId=crypto.randomUUID();$('researchTitle').textContent=prompt.length>72?`${prompt.slice(0,72)}…`:prompt;$('messages').innerHTML='';state.messages=[];addMessage('user',prompt);setRunning(true);setStage('define');const pending=addMessage('assistant','DEFINE — locking the research question, scope, and goal…');try{const health=await request('/health');$('health').textContent=health.version||'ONLINE';await new Promise(r=>setTimeout(r,180));setStage('plan');pending.textContent='PLAN — coordinating the investigation through Unified Master…';await new Promise(r=>setTimeout(r,180));setStage('gather');pending.textContent='GATHER — requesting research output through the existing API contract…';const result=await request('/v1/ai/generate',{method:'POST',body:JSON.stringify({prompt,session_id:state.sessionId})});setStage('verify');pending.textContent='VERIFY — separating the returned findings from unsupported assumptions…';await new Promise(r=>setTimeout(r,180));setStage('synthesize');pending.textContent='SYNTHESIZE — preparing the answer and unresolved questions…';await new Promise(r=>setTimeout(r,180));const answer=(result.text||result.answer||'Research completed without a text response.').toString().trim();pending.remove();state.messages.pop();addMessage('assistant',answer||'Research completed without a text response.');setStage('remember');$('researchState').textContent='COMPLETE'}catch(error){pending.remove();state.messages.pop();addMessage('assistant',`Research could not start: ${error.message}`);$('researchState').textContent='ERROR'}finally{setRunning(false)}}
$('researchForm').addEventListener('submit',event=>{event.preventDefault();startResearch($('prompt').value.trim())});
document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{$('prompt').value=button.dataset.prompt;$('prompt').focus()}));
$('newResearch').addEventListener('click',()=>{state.sessionId=crypto.randomUUID();state.messages=[];$('messages').innerHTML='<div class="empty-state"><div class="empty-icon">✦</div><b>Your research workspace is ready.</b><span>Research output, claims, and verification notes will appear here.</span></div>';$('researchTitle').textContent='Ready for your investigation';$('researchState').textContent='IDLE';$('prompt').value='';setStage('define');window.scrollTo({top:0,behavior:'smooth'})});
$('deepMode').addEventListener('click',event=>{const on=event.currentTarget.querySelector('span');on.textContent=on.textContent==='ON'?'OFF':'ON';event.currentTarget.classList.toggle('enabled')});
request('/health').then(data=>{$('health').textContent=data.version||'ONLINE'}).catch(()=>{$('health').textContent='OFFLINE'});
