from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from collections import defaultdict
from dataclasses import dataclass, asdict
from pathlib import Path, PurePosixPath
from typing import Iterable


TEXT_SOURCE_EXTENSIONS = {
    ".py", ".pyi", ".dart", ".ps1", ".psm1", ".psd1", ".cs", ".csproj", ".sln",
    ".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".html", ".htm", ".css", ".scss",
    ".sh", ".bash", ".zsh", ".bat", ".cmd", ".yml", ".yaml", ".json", ".toml", ".ini",
    ".cfg", ".conf", ".xml", ".plist", ".gradle", ".kts", ".swift", ".m", ".mm", ".h",
    ".hpp", ".c", ".cc", ".cpp", ".rs", ".go", ".java", ".kt", ".md", ".rst", ".txt",
    ".iss", ".lock", ".properties", ".xcconfig", ".entitlements", ".pbxproj", ".xcworkspacedata",
}

ALLOWED_EXTENSIONLESS = {
    "Dockerfile", "Makefile", "Procfile", "Gemfile", "Rakefile", "Podfile", "LICENSE", "NOTICE",
}

BINARY_ASSET_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".icns", ".svg",
}

FONT_EXTENSIONS = {".ttf", ".otf", ".woff", ".woff2", ".eot"}

EXCLUDED_PARTS = {
    ".git", ".dart_tool", ".idea", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "__pycache__", "node_modules", ".venv", "venv", "env", "build", "dist", "out",
    "coverage", "DerivedData", "Pods", ".gradle", ".pub-cache", ".packages", "cache", "temp", "tmp",
}

EXCLUDED_PATH_PREFIXES = (
    "v3/installer/output/",
    "v3/installer/package/runtime/python/",
    "artifacts/",
    "logs/",
    "releases/",
    "release/",
    "backup/",
)

SECRET_PATH_RE = re.compile(
    r"(^|/)(\.env($|\.)|.*\.(pem|pfx|p12|key|keystore|jks)$|credentials?($|[._-])|secrets?($|[._-]))",
    re.IGNORECASE,
)

SECRET_VALUE_PATTERNS = [
    re.compile(rb"\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
    re.compile(rb"AIza[0-9A-Za-z_-]{30,}"),
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
]

GENERATED_MARKERS = (
    b"Generated file. Do not edit.",
    b"GENERATED CODE - DO NOT MODIFY BY HAND",
    b"Generated by the protocol buffer compiler",
)


@dataclass
class RecoveredFile:
    archive_path: str
    original_path: str
    source_commit: str
    source_blob: str
    sha256: str
    size: int


@dataclass
class DuplicateRecord:
    original_path: str
    source_commit: str
    source_blob: str
    matches_path: str
    sha256: str


@dataclass
class ExcludedRecord:
    path: str
    reason: str
    source_commit: str | None = None


def run(*args: str, check: bool = True, text: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        args,
        check=check,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=text,
    )


def git(*args: str, check: bool = True) -> str:
    cp = run("git", *args, check=check, text=True)
    return cp.stdout


def git_bytes(*args: str, check: bool = True) -> bytes:
    cp = run("git", *args, check=check, text=False)
    return cp.stdout


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def normalized(path: str) -> str:
    return str(PurePosixPath(path.replace("\\", "/")))


def is_excluded_path(path: str) -> tuple[bool, str]:
    p = normalized(path)
    pure = PurePosixPath(p)
    parts = set(pure.parts)
    if parts & EXCLUDED_PARTS:
        return True, "generated/cache/dependency directory"
    if any(p.startswith(prefix) for prefix in EXCLUDED_PATH_PREFIXES):
        return True, "generated artifact/output path"
    if SECRET_PATH_RE.search(p):
        return True, "secret-bearing path"
    if pure.suffix.lower() in FONT_EXTENSIONS:
        return True, "font file excluded from shareable source bundle"
    if pure.name.lower() in {"thumbs.db", ".ds_store"}:
        return True, "operating-system metadata"
    return False, ""


def is_project_file(path: str) -> tuple[bool, str]:
    excluded, reason = is_excluded_path(path)
    if excluded:
        return False, reason
    pure = PurePosixPath(path)
    suffix = pure.suffix.lower()
    if suffix in TEXT_SOURCE_EXTENSIONS or suffix in BINARY_ASSET_EXTENSIONS:
        return True, ""
    if pure.name in ALLOWED_EXTENSIONLESS:
        return True, ""
    if pure.name.startswith(".") and pure.name in {".gitignore", ".gitattributes", ".editorconfig"}:
        return True, ""
    return False, "non-source/non-required asset"


def contains_secret(data: bytes) -> bool:
    return any(pattern.search(data) for pattern in SECRET_VALUE_PATTERNS)


def is_generated_text(data: bytes) -> bool:
    prefix = data[:8192]
    return any(marker in prefix for marker in GENERATED_MARKERS)


def list_tree(commit: str) -> list[tuple[str, str, str]]:
    # mode type blob\tpath
    out = git("ls-tree", "-r", "--full-tree", commit)
    entries: list[tuple[str, str, str]] = []
    for line in out.splitlines():
        if not line.strip():
            continue
        meta, path = line.split("\t", 1)
        mode, obj_type, blob = meta.split(" ", 2)
        if obj_type == "blob":
            entries.append((normalized(path), blob, mode))
    return entries


def current_blob_bytes(commit: str, path: str) -> bytes:
    return git_bytes("show", f"{commit}:{path}")


def all_historical_paths() -> list[str]:
    out = git("log", "--all", "--name-only", "--pretty=format:")
    return sorted({normalized(line.strip()) for line in out.splitlines() if line.strip()})


def latest_existing_revision(path: str) -> tuple[str, str] | None:
    commits = git("log", "--all", "--format=%H", "--", path).splitlines()
    for commit in commits:
        if not commit:
            continue
        cp = run("git", "cat-file", "-e", f"{commit}:{path}", check=False, text=True)
        if cp.returncode != 0:
            continue
        blob = git("rev-parse", f"{commit}:{path}").strip()
        return commit, blob
    return None


def branch_provenance() -> list[dict[str, str]]:
    out = git(
        "for-each-ref",
        "--format=%(refname:short)|%(objectname)|%(committerdate:iso8601-strict)|%(subject)",
        "refs/remotes/origin/",
    )
    rows = []
    for line in out.splitlines():
        if not line or line.startswith("origin/HEAD"):
            continue
        name, sha, date, subject = (line.split("|", 3) + ["", "", "", ""])[:4]
        rows.append({"branch": name.removeprefix("origin/"), "sha": sha, "date": date, "subject": subject})
    rows.sort(key=lambda row: (row["date"], row["branch"]))
    return rows


def commit_count() -> int:
    return int(git("rev-list", "--count", "--all").strip())


def first_commit() -> dict[str, str]:
    sha = git("rev-list", "--all", "--reverse").splitlines()[0]
    data = git("show", "-s", "--format=%H|%aI|%s", sha).strip().split("|", 2)
    return {"sha": data[0], "date": data[1], "subject": data[2] if len(data) > 2 else ""}


def copy_latest_tree(repo_root: Path, project_root: Path, target_commit: str):
    active_hash_to_paths: dict[str, list[str]] = defaultdict(list)
    active_blob_to_path: dict[str, str] = {}
    active_file_records: list[dict[str, object]] = []
    excluded: list[ExcludedRecord] = []

    for path, blob, mode in list_tree(target_commit):
        keep, reason = is_project_file(path)
        if not keep:
            excluded.append(ExcludedRecord(path=path, reason=reason, source_commit=target_commit))
            continue
        data = current_blob_bytes(target_commit, path)
        if contains_secret(data):
            excluded.append(ExcludedRecord(path=path, reason="secret pattern detected", source_commit=target_commit))
            continue
        # Generated code in the canonical current tree is kept only if it is part of a required checked-in project.
        # We report it but avoid reconstructing generated build output because those paths are excluded above.
        digest = sha256_bytes(data)
        dst = project_root / path
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(data)
        if mode == "100755":
            dst.chmod(dst.stat().st_mode | 0o111)
        active_hash_to_paths[digest].append(path)
        active_blob_to_path[blob] = path
        active_file_records.append({
            "path": path,
            "blob": blob,
            "sha256": digest,
            "bytes": len(data),
            "generated_marker": is_generated_text(data),
        })

    return active_hash_to_paths, active_blob_to_path, active_file_records, excluded


def recover_historical_unique(
    project_root: Path,
    target_commit: str,
    active_paths: set[str],
    hash_to_paths: dict[str, list[str]],
):
    recovered: list[RecoveredFile] = []
    duplicates: list[DuplicateRecord] = []
    excluded: list[ExcludedRecord] = []
    seen_legacy_hashes: dict[str, str] = {}

    for path in all_historical_paths():
        if path in active_paths:
            continue
        keep, reason = is_project_file(path)
        if not keep:
            excluded.append(ExcludedRecord(path=path, reason=reason))
            continue
        revision = latest_existing_revision(path)
        if revision is None:
            excluded.append(ExcludedRecord(path=path, reason="no recoverable blob"))
            continue
        commit, blob = revision
        data = git_bytes("show", f"{commit}:{path}")
        if contains_secret(data):
            excluded.append(ExcludedRecord(path=path, reason="secret pattern detected", source_commit=commit))
            continue
        digest = sha256_bytes(data)

        if digest in hash_to_paths:
            duplicates.append(DuplicateRecord(
                original_path=path,
                source_commit=commit,
                source_blob=blob,
                matches_path=hash_to_paths[digest][0],
                sha256=digest,
            ))
            continue
        if digest in seen_legacy_hashes:
            duplicates.append(DuplicateRecord(
                original_path=path,
                source_commit=commit,
                source_blob=blob,
                matches_path=seen_legacy_hashes[digest],
                sha256=digest,
            ))
            continue

        archive_path = f"legacy_unique/{path}"
        dst = project_root / archive_path
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(data)
        seen_legacy_hashes[digest] = archive_path
        hash_to_paths[digest].append(archive_path)
        recovered.append(RecoveredFile(
            archive_path=archive_path,
            original_path=path,
            source_commit=commit,
            source_blob=blob,
            sha256=digest,
            size=len(data),
        ))

    return recovered, duplicates, excluded


def current_exact_duplicate_groups(hash_to_paths: dict[str, list[str]]) -> list[dict[str, object]]:
    groups = []
    for digest, paths in sorted(hash_to_paths.items()):
        current_paths = [p for p in paths if not p.startswith("legacy_unique/")]
        if len(current_paths) > 1:
            groups.append({"sha256": digest, "paths": current_paths})
    return groups


def write_reports(
    project_root: Path,
    target_commit: str,
    active_files: list[dict[str, object]],
    recovered: list[RecoveredFile],
    duplicates: list[DuplicateRecord],
    excluded: list[ExcludedRecord],
    branch_rows: list[dict[str, str]],
    exact_duplicate_groups: list[dict[str, object]],
):
    repo = os.environ.get("GITHUB_REPOSITORY", "phakphoum38-stack/ENTERPRISE_API_ARCHITECTURE_LOGIC_TH")
    manifest = {
        "schema": "research-os.unified-source.v1",
        "repository": repo,
        "canonical_target_sha": target_commit,
        "first_reachable_commit": first_commit(),
        "reachable_commit_count": commit_count(),
        "branch_count": len(branch_rows),
        "branches": branch_rows,
        "dedup_policy": {
            "canonical": "latest target tree is the only active source tree",
            "historical": "recover only paths absent from the canonical tree; keep the most recent recoverable revision",
            "content": "historical recovered files are skipped when their SHA-256 already exists in canonical or recovered source",
            "structural_exception": "exact-identical files already present in the canonical latest tree are reported but retained to avoid breaking imports/build structure",
            "generated_outputs": "build/cache/dependency/installer output excluded",
            "secrets": "secret-like paths and detected credential values excluded",
            "fonts": "font binaries excluded from shareable bundle",
        },
        "counts": {
            "canonical_files": len(active_files),
            "historical_unique_files_recovered": len(recovered),
            "historical_duplicates_skipped": len(duplicates),
            "excluded_records": len(excluded),
            "canonical_exact_duplicate_groups_retained": len(exact_duplicate_groups),
        },
        "canonical_files": active_files,
        "historical_unique_files": [asdict(item) for item in recovered],
        "historical_duplicates_skipped": [asdict(item) for item in duplicates],
        "canonical_exact_duplicate_groups_retained": exact_duplicate_groups,
        "excluded": [asdict(item) for item in excluded],
    }
    (project_root / "SOURCE_HISTORY_MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    lines = [
        "# Research OS Unified Source — Deduplication Report",
        "",
        f"Canonical target SHA: `{target_commit}`",
        f"Reachable commits across fetched branches: **{manifest['reachable_commit_count']}**",
        f"Remote branches inspected: **{manifest['branch_count']}**",
        f"Canonical project files retained: **{len(active_files)}**",
        f"Historical unique files recovered once: **{len(recovered)}**",
        f"Historical duplicate files skipped by SHA-256: **{len(duplicates)}**",
        f"Canonical exact-duplicate groups retained for structural correctness: **{len(exact_duplicate_groups)}**",
        f"Excluded generated/cache/dependency/secret/font records: **{len(excluded)}**",
        "",
        "## What 'no duplicate code' means in this bundle",
        "",
        "There is one active canonical project tree only. Older full version trees are not copied beside it.",
        "A historical file is recovered only when its path disappeared from the latest project and its content hash is not already present.",
        "Exact-identical files that already belong to the latest project are reported rather than deleted when removing them could break imports or platform build structure.",
        "",
        "## Historical unique files recovered",
        "",
    ]
    if recovered:
        for item in recovered:
            lines.append(f"- `{item.archive_path}` ← `{item.original_path}` @ `{item.source_commit[:12]}`")
    else:
        lines.append("- None; the latest canonical tree already contains all recoverable source paths.")

    lines += ["", "## Historical duplicate files skipped", ""]
    if duplicates:
        for item in duplicates[:500]:
            lines.append(
                f"- `{item.original_path}` @ `{item.source_commit[:12]}` = `{item.matches_path}` (`{item.sha256[:16]}…`)"
            )
        if len(duplicates) > 500:
            lines.append(f"- … plus {len(duplicates) - 500} additional duplicate records; see SOURCE_HISTORY_MANIFEST.json")
    else:
        lines.append("- None")

    lines += ["", "## Canonical exact-duplicate groups retained", ""]
    if exact_duplicate_groups:
        for group in exact_duplicate_groups[:200]:
            lines.append(f"- `{group['sha256'][:16]}…`: " + ", ".join(f"`{p}`" for p in group["paths"]))
        if len(exact_duplicate_groups) > 200:
            lines.append(f"- … plus {len(exact_duplicate_groups) - 200} groups; see SOURCE_HISTORY_MANIFEST.json")
    else:
        lines.append("- None")

    (project_root / "DEDUP_REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    version_lines = [
        "# Version / Branch Provenance",
        "",
        "This repository has no Git tags at archive time. Version lineage is therefore preserved from all fetched remote branch heads plus full reachable commit history.",
        "",
        "| Date | Branch | SHA | Subject |",
        "|---|---|---|---|",
    ]
    for row in branch_rows:
        subject = row["subject"].replace("|", "\\|")
        version_lines.append(f"| {row['date']} | `{row['branch']}` | `{row['sha'][:12]}` | {subject} |")
    (project_root / "VERSION_PROVENANCE.md").write_text("\n".join(version_lines) + "\n", encoding="utf-8")

    readme = f"""# Research OS Unified Source

This is the deduplicated single-project source archive generated from the complete reachable Git history of `{repo}`.

Canonical active source: `{target_commit}`.

The root tree is the latest project. Historical source that disappeared from the latest tree but is not byte-identical to anything retained is stored once under `legacy_unique/` with commit provenance.

See:
- `SOURCE_HISTORY_MANIFEST.json` for machine-readable provenance and checksums.
- `DEDUP_REPORT.md` for deduplication decisions.
- `VERSION_PROVENANCE.md` for branch/version lineage.

No build caches, dependency directories, installer outputs, detected secrets, private keys, credential files, or font binaries are included.
"""
    (project_root / "UNIFIED_SOURCE_README.md").write_text(readme, encoding="utf-8")


def zip_project(project_root: Path, output_zip: Path):
    output_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for file_path in sorted(project_root.rglob("*")):
            if file_path.is_file():
                arcname = Path(project_root.name) / file_path.relative_to(project_root)
                zf.write(file_path, arcname.as_posix())


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a single deduplicated Research OS source project from complete Git history")
    parser.add_argument("--target", default=os.environ.get("TARGET_SHA", "HEAD"))
    parser.add_argument("--output-dir", default="unified-source-output")
    parser.add_argument("--name", default="Research_OS_UNIFIED_SOURCE_v0.1_to_v3.1")
    args = parser.parse_args()

    target_commit = git("rev-parse", args.target).strip()
    output_dir = Path(args.output_dir).resolve()
    project_root = output_dir / args.name
    if output_dir.exists():
        shutil.rmtree(output_dir)
    project_root.mkdir(parents=True, exist_ok=True)

    hash_to_paths, _, active_files, excluded_current = copy_latest_tree(Path.cwd(), project_root, target_commit)
    active_paths = {str(item["path"]) for item in active_files}
    recovered, duplicates, excluded_history = recover_historical_unique(
        project_root, target_commit, active_paths, hash_to_paths
    )
    duplicate_groups = current_exact_duplicate_groups(hash_to_paths)
    branches = branch_provenance()
    excluded = excluded_current + excluded_history

    write_reports(
        project_root,
        target_commit,
        active_files,
        recovered,
        duplicates,
        excluded,
        branches,
        duplicate_groups,
    )

    output_zip = output_dir / f"{args.name}_{target_commit[:12]}.zip"
    zip_project(project_root, output_zip)
    digest = sha256_file(output_zip)
    checksum_path = output_dir / f"{output_zip.name}.sha256"
    checksum_path.write_text(f"{digest}  {output_zip.name}\n", encoding="ascii")

    summary = {
        "target_sha": target_commit,
        "project_dir": str(project_root),
        "zip": str(output_zip),
        "zip_sha256": digest,
        "zip_bytes": output_zip.stat().st_size,
        "canonical_files": len(active_files),
        "historical_unique_files": len(recovered),
        "historical_duplicates_skipped": len(duplicates),
        "canonical_exact_duplicate_groups_retained": len(duplicate_groups),
        "branches": len(branches),
        "commits": commit_count(),
    }
    (output_dir / "BUILD_SUMMARY.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
