#!/usr/bin/env python3
"""Generate target-bound runtime evidence and a provenance ledger."""
from __future__ import annotations
import argparse, hashlib, json, os, subprocess
from datetime import datetime, timezone
from pathlib import Path
DOMAIN=b"provenance-entry-v1\x00"; ROOT=Path(__file__).resolve().parents[1]
def canonical(value: object)->str:return json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False)
def plain_digest(value: object)->str:return hashlib.sha256(canonical(value).encode()).hexdigest()
def digest(value: object)->str:return hashlib.sha256(DOMAIN+canonical(value).encode()).hexdigest()
def git(*args:str)->str:return subprocess.check_output(["git",*args],cwd=ROOT,text=True).strip()
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--output-dir",default="target-provenance");p.add_argument("--target-commit",default=None);a=p.parse_args();out=ROOT/a.output_dir;out.mkdir(parents=True,exist_ok=True);target=a.target_commit or git("rev-parse","HEAD");source=git("rev-parse",f"{target}^");run_id=os.environ.get("GITHUB_RUN_ID","unknown");workflow=os.environ.get("GITHUB_WORKFLOW","Provenance Evidence Gate");recorded_at=datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z");changed=git("diff-tree","--no-commit-id","--name-only","-r",target).splitlines();tree=git("show","-s","--format=%T",target);evidence={"schema_version":"1.0","evidence_id":f"EV-TARGET-{target[:12]}","workflow":workflow,"run_id":run_id,"target_commit":target,"source_commit":source,"commit_tree":tree,"changed_paths":changed,"recorded_at":recorded_at};ep=out/"TARGET_BOUND_EVIDENCE.json";ep.write_text(json.dumps(evidence,indent=2,sort_keys=True,ensure_ascii=False)+"\n",encoding="utf-8");er=plain_digest(evidence);aid=f"AT-TARGET-{target[:12]}";att={"entry_id":aid,"sequence":1,"recorded_at":recorded_at,"actor_id":"github-actions:provenance-evidence-gate","action":"attest_target_generation","subject_type":"git-commit","subject_id":target,"input_hashes":{"source_commit":{"algorithm":"git-sha1","digest":source,"subject":"git-commit"}},"output_hashes":{"target_commit":{"algorithm":"git-sha1","digest":target,"subject":"git-commit"},"evidence":{"algorithm":"sha256","digest":er,"subject":"artifact:target-provenance/TARGET_BOUND_EVIDENCE.json"}},"evidence_type":"attestation","evidence":{"attestation_id":aid,"subject_id":target,"attester_id":"github-actions:provenance-evidence-gate","statement":"The exact target generation and its runtime evidence were observed in this workflow run.","evidence_ids":[],"issued_at":recorded_at},"previous_entry_hash":None};att["entry_hash"]=digest(att);ledger={"contract_version":"1.1.0","entries":[att]};lp=out/"TARGET_BOUND_PROVENANCE.json";lp.write_text(json.dumps(ledger,indent=2,sort_keys=True,ensure_ascii=False)+"\n",encoding="utf-8");pr=plain_digest(ledger);roots={"schema_version":"1.0","target_commit":target,"source_commit":source,"evidence_root":er,"provenance_root":pr,"evidence_file":str(ep.relative_to(ROOT)).replace("\\","/"),"provenance_file":str(lp.relative_to(ROOT)).replace("\\","/")};(out/"TARGET_BOUND_ROOTS.json").write_text(json.dumps(roots,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(json.dumps(roots,sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
